name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_and_upload:

    runs-on: ubuntu-latest

    steps:
      -
        name: code checkout
        uses: actions/checkout@v3
      -
        name: login to docker hub
        uses: docker/login-action@v3
        with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}
      -
        name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context:
          file: ../../Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/usernamanagement:$(date +%s)