name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_and_upload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    - name: docker login
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag usernamagement-learning:$(date +%s)

    - name: docker push to upload the image to docker hub
      run: docker push rajguru-repo/usernamagement-learning:$(date +%s)


